version: "3.8"

services:
  elasticsearch:
    container_name: log_system_elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.7.1"
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - log_system_elasticsearch_data:/usr/share/elasticsearch/data
      
  kibana:
    container_name: log_system_kibana
    image: "docker.elastic.co/kibana/kibana:8.7.1"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: elasticsearch:9200
  
volumes:
  log_system_elasticsearch_data: